apiVersion: apps/v1
kind: Deployment
metadata:
  name: mountbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mountbook
  template:
    metadata:
      labels:
        app: mountbook
    spec:
      containers:
        - name: mountbook
          image: lucamuraz/mountbook
          envFrom:
            - configMapRef:
                name: mountbook-configmap
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mountbook
spec:
  type: LoadBalancer
  ports:
    - name: mountbook
      port: 8081
      targetPort: 8081
  selector:
    app: mountbook